server:
    port: 8081
spring:
    application:
        name: SpringBootRunner
    datasource:
        master:
            driverClassName: com.mysql.jdbc.Driver
            masterMapperLocations: classpath:mybatis/master/*.xml
            password: WQY1234
            url: jdbc:mysql://localhost:3306/springboot
            username: root
    mail:
        host: smtp.qq.com
        password: 'IMAP/SMTP服务独立密码 用于第三方登录邮箱 '
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
        username: 896943899@qq.com
    profiles:
        active: dev
    redis:
        cluster:
            nodes: 192.168.129.174:16379 , 192.168.129.175:16379 ,192.168.129.176:16379
    security:
        user:
            name: admin
            password: admin
